### PR TITLE
Implemented noise contrastive estimation and learning to rank losses

### PR DESCRIPTION
**Pull request by ijskar**
This contribution adds the [noise contrastive estimation](https://www.ijcai.org/proceedings/2021/390) and the [learning to rank](https://proceedings.mlr.press/v162/mandi22a.html) losses for decision-focused learning to PyEPO. Both of these approaches make use of the solution caching scheme that is already implemented in PyEPO.

Concretely, the following changes are included:

- a new file named `learning_to_rank.py`, which includes an abstract `LearningToRank` class, as well as three concrete subclasses for the different learning to rank methods: `ListwiseLTR`, `PairwiseLTR` and `PointwiseLTR`.
- a new file named `nce.py`, which includes the `NCE` class, which implements the noise contrastive estimation loss.
- the use of the listwise learning to rank method has been added to the `03 Training and Testing.ipynb` notebook.
- the `README.md` file has been updated to include the new methods.

### CODE REVIEW

**Comment by LucasBoTang** [comment]
Hi ijskar,

Thank you for your great contribution to the PyEPO project. Your additions of noise contrastive estimation and learning to rank losses are a solid enhancement to our project.

I see you've integrated it well with our existing features, and your explanation is clear. I am enthusiastic about reviewing your pull request. I will do so as promptly as possible and provide feedback or suggestions if necessary. 

Thanks again for your time and efforts!

**Comment by LucasBoTang** [comment]
It was merged on #10 to NEC branch for further review. Thank you @ijskar !

**Comment by LucasBoTang** [comment]
Hi @ijskar,
I have a question about the use of "np.unique" in your code for PairwiseLTR ([line 137](https://github.com/ijskar/PyEPO/blob/f9e1127308bc4a7ac42c180fe90aba2d8a0887a3/pkg/pyepo/func/learning_to_rank.py#L137C22-L137C22)). I noticed that it's used to sort and remove duplicates. I'm curious about the significance of this action and if we could possibly find the argmin and make comparisons with the rest (with duplication). Could you please shed light on this?

**Comment by ijskar** [comment]
Hi @LucasBoTang,

Indeed, the "np.unique" removes duplicates and sorts the solution pool. We could indeed also just find the argmin and compare with the rest. That might be more consistent w.r.t. the other learning to rank methods, since duplicates aren't removed in those methods.

However, I think that it might be even better to simply not allow duplicates in the solution pool at all. Not only will this limit the size of the pool, but it also makes more sense in the context of the ranking methods. Duplicate solutions are currently ranked over multiple times, and thus have a larger effect on the ranking losses than unique solutions, but this is not intended. Perhaps whenever a solution is to be added to the pool, we can first check whether it is already present in the pool, and only add it if it isn't. What do you think about this?

**Comment by LucasBoTang** [comment]
Hi @ijskar ,

Thank you for explaining the use of "np.unique". Indeed, I concur with your viewpoint on keeping the solution pool unique. It makes much sense.

In fact, I had the same ideas before, and I modified the solution pool to only keep unique solutions yesterday (see the commit "[New feat: unique solpool](https://github.com/khalil-research/PyEPO/commit/c4278f063c8d76c9cf1f6a4cb96a603917470371)"). This adjustment was incorporated into our code base yesterday, which also seems slightly improve the performance.

Also, I have completed the review of your pull request. Therefore, I have now merged your contribution into the main branch of the PyEPO repository. Given that there have been changes in the code, you can also review the modified code when you get a chance.

**Pull request merged**
